name: PR build
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Check NodeJS environment
        run: |
          echo "node: $( node -v )"
          echo "npm: $( npm -v )"
          echo "npx: $( npx -v )"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Tests
        run: npm run test
      - name: Build
        run: npm run build:prod
